### ISSUE TITLE
Contracts with non-overlapping `startBlock`/`endBlock`

### ISSUE THREAD

**Issue by 0xOlias** [ponder-sh/ponder#507]
A user reported a bug where either indexing did not start, or the sync did not start under this scenario.
```
contract1:
  startBlock: 10
  endBlock: 100
contract2:
  startBlock: 1000
```
Let's verify and add tests for this.
